export const GET_ALL_WORDS = "GET_ALL_WORDS";
export const GET_USER_WORDS = "GET_USER_WORDS";
export const ADD_WORD = "ADD_WORD";
export const DELETE_WORD = "DELETE_WORD";
export const WORDS_LOADING = "WORDS_LOADING";
export const ADD_WORD_FAIL = "ADD_WORD_FAIL";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SETTINGS_LOADING = "SETTINGS_LOADING";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_DRAWING_WORD = "SET_DRAWING_WORD";
export const SET_CURRENT_DRAWER = "SET_CURRENT_DRAWER";
export const SET_CURRENT_TIME = "SET_CURRENT_TIME";
export const SET_GAME_TIME = "SET_GAME_TIME";
export const SET_ROOM_USERS = "SET_ROOM_USERS";
export const SET_ROOM = "SET_ROOM";
export const SET_GAME_STARTED = "SET_GAME_STARTED";
